# permissions for end users to view mutualcpus.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: mutualcpu-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: mutualcpu-operator
    app.kubernetes.io/part-of: mutualcpu-operator
    app.kubernetes.io/managed-by: kustomize
  name: mutualcpu-viewer-role
rules:
- apiGroups:
  - mutualcpu.openshift.io
  resources:
  - mutualcpus
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - mutualcpu.openshift.io
  resources:
  - mutualcpus/status
  verbs:
  - get
